version: '3.7'

services:
  scustoms:
    image: scustoms:latest
    restart: "no"
    volumes:
      - "../database:/opt/docker/database/"
    environment:
      #- DISCORD_SCUSTOMS_TOKEN=$DISCORD_SCUSTOMS_TOKEN
      - DISCORD_SCUSTOMS_TOKEN=OTE2MDQ0OTY2NDI4NTUzMjc4.YakbWw.v44SRosnWJ_KF2AcMUkHXiZ1WbQ
    networks:
      backend:

networks:
  backend:        
