version: '3.7'

services:
  scustoms:
    image: scustoms:latest
    restart: "no"
    volumes:
      - "../database:/opt/docker/database/"
    environment:
      - DISCORD_SCUSTOMS_TOKEN=$DISCORD_SCUSTOMS_TOKEN
    networks:
      backend:

networks:
  backend:
